---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  namespace: staging
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/target-type: ip
spec:
  type: LoadBalancer
  selector:
    run: php-apache
  ports:
    - port: 80
      targetPort: 80
