---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: triptribe-k8s
  namespace: staging
spec:
  selector:
    matchLabels:
      app: triptribe-k8s
  template:
    metadata:
      labels:
        app: triptribe-k8s
    spec:
      containers: 
        - name: triptribe-k8s
          image:xxx
          ports: 
            - containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi


