name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - dev

jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 

      - name: Install AWS CLI
        run: |
          sudo apt-get -y install python3-pip
          pip3 install awscli --upgrade --user

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-southeast-2

      - name: Build Nest.js application
        run: |
          npm install
          npm run build

      - name: Zip deployment package
        run: |
          zip -r deployment-package.zip .

      - name: Upload deployment package to AWS S3
        run: |
          aws s3 cp deployment-package.zip s3://triptribe/

      - name: Create Elastic Beanstalk application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name TripTribe \
            --version-label V12 \
            --source-bundle S3Bucket=triptribe,S3Key=deployment-package.zip

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --application-name TripTribe \
            --environment-name TripTribe-dev \
            --version-label V12
